service: dartscore-lambda

provider:
  name: aws
  runtime: python3.8
  role: arn:aws:iam::#{AWS::AccountId}:role/dartscore-lambda-role
  region: us-east-1
  logs:
    websocket: true

package:
  include:
    - dependencies/**
  exclude:
    - .coverage
    - .git
    - .gitignore
    - ez_setup.py
    - MANIFEST.in
    - requirements.pip
    - setup.cfg
    - setup.py
    - test-requirements.pip
    - docs/**
    - reports/**
    - test/**
    - .tox/**
    - node_modules/**

plugins:
  - serverless-pseudo-parameters


functions:
  generate_id:
    handler: create.generate_id
    description: Generates a new game id
    events:
      - http:
          path: /generateid
          method: GET
          cors: true
  create_game:
    handler: create.create_game
    description: Creates a game and adds it to the table
    events:
      - http:
          path: /create
          method: POST
          cors: true
  lobby:
    handler: state.lobby
    description: fetches the state of the lobby
    events:
      - http:
          path: /lobby
          method: GET
          cors: true
  socket:
    handler: socket.lambda_handler
    description: Lamdbda socket handler
    events:
      - websocket: $connect
